-- create space table in database by jie meng
DROP TABLE IF EXISTS`space`;
CREATE TABLE IF NOT EXISTS `space` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `category` varchar(50) NOT NULL,
  `name` varchar(100) NOT NULL,
  `type` varchar(255) NOT NULL,
  `year` int(10) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB  DEFAULT CHARSET=latin1 AUTO_INCREMENT=1 ;

--
-- poulating data for table `space`
--

INSERT INTO `space` (`id`, `category`, `name`, `type`,`year`) VALUES
(1, 	'Movies', 'Interstellar', 'Space Exploration',2014),
(2, 	'Movies', 'The Maetian','Space Exploration', 2015),
(3, 	'Movies', '2001: A Space Odyssey','Space Exploration', 1968),
(4,		'Movies','Ghost in the Shell','Advanced Technolofy',2017),	
(5,		'Movies','Minority Report','Advanced Technolofy',2002),	
(6, 	'Movies','A.I. Artificial Intelligence','Advanced Technolofy',2001),	
(7,		'Movies','Tent','Time Travel',2020),
(8,	 	'Movies','The Adam Project','Time Travel',2022),
(9,		'Movies','Back to the Future','Time Travel',1985),	
(10, 	'Movies','Everything Everywhere All at Once','Parallel Universes',2022),	
(11, 	'Movies','Doctor Strange','Parallel Universes',2016),
(12, 	'Movies','Spider-Man: No Way Home','Parallel Universes',2021),	
(13,    'Movies','Arrival','Alien Lifefroms',2016),
(14,	'Movies','Avatar', 'Alien Lifefroms',2009),	
(15,    'Movies','Independence Day','Alien Lifefroms',1996),	
(16,	'Movies','Black Adam','Coming Soon',2022),	
(17,	'Movies','Interstellar','Coming Soon',2014),	
(18,	'Movies','Moonfall','Coming Soon',2022),	
(19,	'TV Series','The Orville','Space Exploration',2017),	
(20,	'TV Series','The Expanse','Space Exploration',2015	),
(21,	'TV Series','Star Trek: Strange New Worlds','Space Exploration',2022),	
(22,	'TV Series','Black Mirror','Advanced Technolofy',2011),	
(23,	'TV Series','Made for Love','Advanced Technolofy',2021),	
(24,	'TV Series','Humans','Advanced Technolofy',2015	),
(25,	'TV Series','The Time Travelers Wife','Time Travel',2022),	
(26,	'TV Series','Timeless',	'Time Travel',2016	),
(27,	'TV Series','Future Man','Time Travel',2017),	
(28,	'TV Series','Fringe','Parallel Universes',2008),	
(29,	'TV Series','Stranger Things','Parallel Universes',2016	),
(30,	'TV Series','Zapped','Parallel Universes',2016	),
(31,	'TV Series','Doctor Who','Alien Lifefroms',2005	),
(32,	'TV Series','Resident Alien','Alien Lifefroms',2021),	
(33,	'TV Series','Halo','Alien Lifefroms',2022),	
(34,	'TV Series','The Three-Body Problem','Coming Soon',2025	),
(35,	'TV Series','Paper Girls','Coming Soon',2022),	
(36,	'TV Series','The Imperfects','Coming Soon',2022	),
(37,	'Animations','Edens Zero','Space Exploration',2021),	
(38,	'Animations','Final Space','Space Exploration',2018	),
(39,	'Animations','Cowboy Bebop','Space Exploration',2021),	
(40,	'Animations', 'Love, Death & Robots','Advanced Technolofy',2019	),
(41,	'Animations','Ghost in the Shell SAC_2045','Advanced Technolofy',2020),	
(42,	'Animations','Big Hero 6','Advanced Technolofy',2014),	
(43,	'Animations','Futurama','Time Travel',1999	),
(44,	'Animations','The Girl Who Leapt Through Time',	'Time Travel',2006	),
(45,	'Animations','Your Name','Time Travel',	2017),	
(46,	'Animations','Rick and Morty','Parallel Universes',2013	),
(47,	'Animations','Spider-Man: Into the Spider-Verse','Parallel Universes',2018),	
(48,	'Animations','Steins Gate','Parallel Universes',2011),	
(49,	'Animations','Solar Opposites',	'Alien Lifefroms',2020	),
(50,	'Animations','Star vs. the Forces of Evil','Alien Lifefroms',2015),	
(51,	'Animations', 'Invader ZIM', 'Alien Lifefroms',	2001),	
(52,	'Animations','Farzar','Coming Soon',2022),	
(53,	'Animations','Bubble','Coming Soon',2022);